image: registry.gitlab.com/floodcode/project-neo/ci:latest

stages:
  - deploy

deploy_production:
  stage: deploy
  when: manual
  environment:
    name: production
    url: http://project-neo.tk
  only:
    - tags
  script:
    # Prepare build to deployment
    - 'mkdir -p /var/www/releases'
    - 'cp -r . /var/www/releases/current'
    - 'cd /var/www/releases/current'
    - 'cp .env.host .env'
    - 'php composer.phar install --optimize-autoloader --no-dev --no-progress'
    - 'php artisan config:cache'
    - 'php artisan route:cache'
    # Configure SSH
    - 'mkdir -p ~/.ssh'
    - 'eval $(ssh-agent -s)'
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
    - 'ssh-add <(echo "$SSH_PRIVATE_KEY")'
    # Upload new release to the host
    - 'scp -r . $SSH_USER@$SSH_HOST:~/releases/new'
    # Run deploy script on the host
    - 'ssh -p 22 $SSH_USER@$SSH_HOST "docker exec project-neo bash /var/www/releases/new/bin/deploy.sh"'